terraform:
  - changed-files:
    - any-glob-to-any-file:
      - 'kops-init/*.tf'
      - 'kops-infra/*.tf'
      - 'tf-modules/*/*.tf'
      - 'tf-modules/*/*.tfvars'

kubernetes:
  - changed-files:
    - any-glob-to-any-file:
      - 'scripts/create-cluster.sh'
      - 'scripts/destroy-cluster.sh'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - 'README.md'
      - 'scripts/README.md'
      - 'tf-modules/envs/README.md'
      - 'kops-init/README.md'

ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**'
      - '.gitignore'